language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"
 - "pypy"
 - "pypy3"

env:
  global:
   - secure: "UkS0YsOipSqIw/UzUdKnE7UdGKmT/5ljLrHDlbHHnfKeWDowes8cWXW2vCVu4FhIwAhHsCFPF5h9j0pLPpBt38aMPbTe9ijKwXsM1/HxMklMoxMx4iVbWXa9W9d1nHNgKxDayeBOpYiCcrvAgy9BaLVrP+cPJCVOvrPWE8VX8iZTq7wgehPivFg4bCRN4TosWTXm+f9ARSdQEuTf/ouy7OCsGTBEFaHph6y9wdcoZO+nhGowyEP8HGi/YnnQYkqsuCpjZE9q/mh8TFgjY32flSoP9KBq0RHTXyI4455O/J9LfYhPZGgJhwP+V7r5oS6JIb+j8MMhUcxz1oGrsELwATPY0cP53clQtoyxoFnBWcP8ySfnByaDMj7SVNYzRGrwsiizcTkUrEXeZmhDAnsgGOQcGKIcInqgBDawXuGOMcN7dh/+2tAbVGh6jbG9bUXtWUj2pRDa35IEbVBTcnHMQ0tlJKredZ+VttfAvm/m/FVs1pLfrW6lbiFo3sgZkStsgUjqJlpOkckw1BlJ7+6OG+fFMi4xjIJNrb14YZA8qtZI3dT0Oqn4nGPesm4K8Ff624mAnvWowAZWI+1jNrhcnXXdCBOZzHPpQwMcNeKdeaDZIrUAJ+lWm6Ip6vlRA1NHaFr48AZWCgqspqQAeEkvHVrZqWQkYp7SwT6oucBwYuY=" # GITHUB_API_TOKEN

install:
 - pip install tox-travis
 - pip install -e .

script: tox
